# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl-Compare
version:      0.07
version_from: lib/Perl/Compare.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    File::Spec:                    0.82
    List::MoreUtils:               0
    List::Util:                    1.11
    PPI:                           0.829
    Scalar::Util:                  1.11
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
